version: 0.1

phases:
  build:
    commands:
      # Use AWS SAM to package the application by using AWS CloudFormation
      - aws s3 cp --recursive src/ s3://$WEBSITE_S3_BUCKET/public/ --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      
artifacts:
  files:
    - index.html
    - favicon.ico
    - styes/main.css
    - images/*
    
